title: Earthquake map
hero_image: images/banner.png
description:
version: 4
listed: false
copyedit: false
last_tested: "2018-12-06"
steps:
  - title: Introduction
  - title: Finding earthquakes near a location
  - title: Separating the data
  - title: Plotting the data
  - title: Improving the plot
  - title: Challenge: improve your map